//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nfit
{
    using System;
    using System.Collections.Generic;
    
    public partial class osmotry
    {
        public osmotry()
        {
            this.predpisanya = new HashSet<predpisanya>();
        }
    
        public int Id_osmotra { get; set; }
        public int Id_pacienta { get; set; }
        public int Id_vracha { get; set; }
        public System.DateTime data_osmotra { get; set; }
        public string rezult_osmotra { get; set; }
        public string rec_vracha { get; set; }
        public string diagnoz { get; set; }
    
        public virtual pacienty pacienty { get; set; }
        public virtual vrachi vrachi { get; set; }
        public virtual ICollection<predpisanya> predpisanya { get; set; }
    }
}
