//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nfit
{
    using System;
    using System.Collections.Generic;
    
    public partial class pacienty
    {
        public pacienty()
        {
            this.osmotry = new HashSet<osmotry>();
            this.users = new HashSet<users>();
        }
    
        public int Id_pacienta { get; set; }
        public string fio { get; set; }
        public System.DateTime birthday { get; set; }
        public string pol { get; set; }
        public string nomer_tel { get; set; }
    
        public virtual ICollection<osmotry> osmotry { get; set; }
        public virtual ICollection<users> users { get; set; }
    }
}
