//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nfit
{
    using System;
    using System.Collections.Generic;
    
    public partial class predpisanya
    {
        public int Id_predpisanya { get; set; }
        public int id_osmotra { get; set; }
        public string naznachenie { get; set; }
        public string dozirovka { get; set; }
        public string srok_priema { get; set; }
    
        public virtual osmotry osmotry { get; set; }
    }
}
