//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nfit
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public int Id_usera { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public string role { get; set; }
        public string ФИО { get; set; }
        public Nullable<int> id_pacienta1 { get; set; }
    
        public virtual pacienty pacienty { get; set; }
    }
}
