//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nfit
{
    using System;
    using System.Collections.Generic;
    
    public partial class vrachi
    {
        public vrachi()
        {
            this.osmotry = new HashSet<osmotry>();
        }
    
        public int Id_vracha { get; set; }
        public string fio1 { get; set; }
        public int staj { get; set; }
        public string specializaciya { get; set; }
        public string nomer_tela { get; set; }
        public string photo { get; set; }
    
        public virtual ICollection<osmotry> osmotry { get; set; }
    }
}
